### ISSUE TITLE
Support for cluster volumes

### ISSUE THREAD

**Issue by TheSilkky** [aaraney/deployx#2]
I noticed when trying to deploy a stack that uses cluster volumes, deployx will output this error:
`service name_of_service: volume type must be volume, bind, tmpfs, or npipe`

Cluster volumes are a part of swarm and should be supported by deployx, however they aren't apart of the compose-spec which might be an issue

[Cluster Volumes (CSI) docs](https://github.com/moby/moby/blob/master/docs/cluster_volumes.md)

Example:
```
postgres:
  image: postgres:15.3-alpine3.18
  hostname: postgres
  networks:
    - backend
  volumes:
    - type: cluster
      source: postgres_database
      target: /var/lib/postgresql/data
  secrets:
    - source: database_password
      mode: 0600
  environment:
    - POSTGRES_DB=example
    - POSTGRES_USER=example
    - POSTGRES_PASSWORD_FILE=/run/secrets/database_password
    - PGDATA=/var/lib/postgresql/data/pgdata
```
